### ISSUE TITLE
detector_node dies due to invalid canny parameters

### ISSUE THREAD

**Issue by amartyadash** [AerialRobotics-IITK/ariitk_fpv_racing#7]
On launching basic_track.launch the detector node dies after throwing an instance of `cv::Exception` : 
```bash
error: (-206) Aperture size should be odd between 3 and 7 in function Canny
```

**Comment by ashwin2802** [comment]
fixed. `basic_track.launch` doesn't have the param file. remind me to merge it in the next PR
